[phases.setup]
nixPkgs = ["python312", "quarto"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["cd site && quarto render && cd .."]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"
